var sumerSays = [
    `Who can compete with righteousness? It creates life. (1.1)`,
    `If wickedness exerts itself, how will Utu succeed? (1.2)`,
    `You should not cut the throat of that which has already had its throat cut. (1.3)`,
    `You should not say to Ningi\u0161zida: "Let me live!" (1.4)`,
    `Do not make me pass through the gate! (1.5)`,
    `What has submitted will exhibit resistance. (1.6)`,
    `What has been destroyed belongs to a god. No one is able to take it away. (1.7)`,
    `"Though I still have bread left over, I will eat your bread!" Will this endear a man to the household of his friend? (1.8)`,
    `If bread is leftover, the mongoose eats it. If I have any bread left over, then a stranger will eat it. (1.9)`,
    `My things changed things. (1.10)`,
    `You don't speak of that which you have found. You talk only about what you have lost. (1.11)`,
    `Something which has never occurred since time immemorial: a young woman did not fart in her husband's embrace. (1.12)`,
    `It is a thing of short duration. (1.13)`,
    `Whatever it is that hurts you, don't talk to anyone about it. (1.14)`,
    `Wealth is far away, poverty is close at hand. (1.15)`,
    `He who possesses many things is constantly on guard. (1.16)`,
    `Possessions make trust of crucial importance. (1.17)`,
    `Possessions are flying birds--they never find a place to settle. (1.18)`,
    `Good fortune is embedded in organization and wisdom. (1.19)`,
    `What is eaten for today (?) was put there by the dog. What is eaten by the dog was put there for today (?). (1.20)`,
    `One shouldn't scorn bread which has turned bad. (1.21)`,
    `Give out only half a loaf voluntarily! (1.22)`,
    `To be wealthy and insist on demanding more is abominable. (1.23)`,
    `Let him decree the fates while consuming what you have made. (1.26)`,
    `I always seem to be speaking about unpleasant things. (1.27)`,
    `When a purchase is settled it is soon out of mind. (1.28)`,
    `He did something never seen before. (1.29)`,
    `That which does not eat grass is a wild bull of the mountains. That which does not drink water is a gazelle of the mountains. (1.30)`,
    `One does not returned borrowed bread. (1.31)`,
    `The herald rejoices when the estate makes expenditures. (1.32)`,
    `The steward rejoices when the estate increases its income. (1.33)`,
    `Don't pick things now; they will bear fruit later. (1.35)`,
    `Who will listen to your translations? (1.36)`,
    `What you are doing is a small accomplishment. That man is not doing a man's work. (1.37)`,
    `Let his bread be foul food; no man should eat it. (1.40)`,
    `Let his food be bread and ... eggs, so that it clogs his throat. (1.41)`,
    `Let his food be ... bones, so that it sticks in his throat. (1.42)`,
    `Barley flour, in the fields, is meat fat. (1.48)`,
    `Whatever food is available in the fields is to be eaten alone. (1.49)`,
    `Chickpea-flour is appropriate for every woman in the palace. (1.50)`,
    `His bread is finished. (1.51)`,
    `There is no baked cake in the middle of the dough. (1.52)`,
    `Give me my tools and I will launch my boat. (1.54)`,
    `When he walks on the streets no one greets him. And when he comes home to his wife, "Bad Name" is what he is called. (1.56)`,
    `The lives of the poor do not survive their deaths. (1.57)`,
    `In the city where there are no dogs, the fox is boss. (1.65)`,
    `You should drive them like pack-assess into a death-stricken city (1.68)`,
    `Like a clod thrown into the water, may it be destroyed as it disintegrates. (1.76)`,
    `Beer is a bull. The mouth is its stairway. (1.77)`,
    `It is an insult resulting from an insult. It is a curse resulting from a curse. It is the constant renewal of destiny. (1.80)`,
    `To accept a verdict is possible. To accept a curse is impossible. (1.81)`,
    `My girlfriend's heart is a heart made for me. (1.91)`,
    `He broke it into pieces and sated his hunger. He licked his hands and belched. (1.101)`,
    `He who drinks beer drinks water. (1.102)`,
    `A heart never created hatred; speech created hatred. (1.105)`,
    `(line fragmentary)`,
    `You cannot butt me with your horns! Who is it that you are butting! You cannot kill me--I am running away! (1.109)`,
    `My husband heaps up for me, my child measures out for me; let my lover pick the bones from the fish for me. (1.125)`,
    `A plant as sweet as a husband does not grow in the steppe. (1.126)`,
    `In the sky there is the raven; on the earth there is the mongoose; in the desert there is the lion ...; my husband! Where shall I go? (1.128)`,
    `...the brothers in anger destroyed their father's estate. (1.141)`,
    `Thus my mother and my younger sister act toward me; ... am I so deficient in judgment that I should offer my cheek to her? (1.143)`,
    `You are not one who stays in one place, you are one who is everywhere. (1.144)`,
    `Accept your lot and make your mother happy. Run fast and make your god happy. (1.145)`,
    `Marry a wife according to your choice. Have children to your heart's content. (1.146)`,
    `Girl, your brother cannot choose for you; whom do you choose? (1.148)`,
    `Girl, your brother is like me. A brother should let you live as would I. (1.149)`,
    `When I married a malicious husband, when I bore a malicious son, an unhappy heart was assigned to me. (1.151)`,
    `He who does not support a wife, he who does not support a child, has no cause for celebration. (1.153)`,
    `A malicious wife living in the house is worse than all diseases. (1.154)`,
    `My wife said "Unfaithful!" to me--shall I go chasing after women's genitals? (1.158)`,
    `An unfaithful penis matches an unfaithful vagina. (1.159)`,
    `What...? A tradesman gave it to me... (1.164)`,
    `I walk about, I don't get tired. I keep moving, I don't sleep. (1.174)`,
    `When the rags have been cut up, when the barley is lying in the dust, what is there left to get? (1.175)`,
    `I am a lady who wears large garments. Let me cut my loincloth! (1.176)`,
    `When you are eating, may nothing lack. When you are in need of water, may things not dry up. (1.178)`,
    `A chattering girl is silenced by her mother. A chattering boy is not silenced by his mother. (1.185)`,
    `To be sick is acceptable; to be pregnant is painful; but to be pregnant and sick is just too much. (1.193-194)`,
    `Let me explain it to you: it is a disgrace. (2.1)`,
    `Were I to tell my neighbor about my fate, he would heap insults upon me. (2.3)`,
    `I looked into the water. My destiny was drifting past. (2.4)`,
    `I was born on an ill-fated day. (2.15)`,
    `Fate is a dog--well able to bite. Like dirty rags, it clings, saying: "Who is my man? Let him know it." (2.11)`,
    `Fate is a cloth stretched out in the desert for a man. (2.12)`,
    `Fate is a raging storm blowing over the Land. (2.13)`,
    `Fate is a dog walking always behind a man. (2.14)`,
    `The poor man must always look to his next meal. (2.15)`,
    `The belching poor man should not look scornfully at the rich man. (2.16)`,
    `How can a poor man who doesn't know how to cultivate barley manage to cultivate wheat? (2.17)`,
    `The poor man is not appreciated. (2.18)`,
    `The poor man chews whatever he is given. (2.19)`,
    `He didn't plough the field during winter. And at harvest time he turned his hand to carding. (2.20)`,
    `Not all the households of the poor will bow down together. (2.26)`,
    `The word of the poor man is not accepted. (2.27)`,
    `Moving about defeats poverty. He who knows how to move around becomes strong. He will live longer than the sedentary man. (2.28)`,
    `The poor man is this lowly: his debts are paid off with what is taken from his mouth. (2.30)`,
    `You are a scribe and you do not know your own name? Shame on you! (2.37)`,
    `If a scribe knows only a single line but his handwriting is good, he is indeed a scribe! (2.38)`,
    `If a singer knows only one song but makes the sound pleasant, he is indeed a singer! (2.39)`,
    `A scribe whose hand can follow dictation is indeed a scribe! (2.40)`,
    `A singer whose voice is not sweet is a wretch among singers! (2.41)`,
    `A wretched scribe, the most backward in the school! (2.42)`,
    `A scribe without a hand. A singer without a throat. (2.43)`,
    `You are an outstanding scribe; you are no lowly man. (2.44)`,
    `The pupil of a master, like cornelian pierced through its side. He is indeed a scribe! (2.45)`,
    `That which is pierced through its side is indeed lapis lazuli! (2.46)`,
    `What kind of scribe is a scribe who does not know Sumerian? (2.47)`,
    `Someone who cannot produce "a-a"--from where will he achieve fluent speech? (2.48)`,
    `A scribe who does not know Sumerian--from where will he produce a translation? (2.49)`,
    `The scribe trained in counting is deficient on clay. The scribe skilled with clay is deficient in counting. (2.50)`,
    `You are a ... scribe ... (2.51)`,
    `A chattering scribe's guilt is great. (2.52)`,
    `A junior scribe is too concerned with feeding his hunger; he does not pay attention to the scribal art. (2.53)`,
    `A scribe who does not know how to grasp the meaning--from where will he produce a translation? (2.56)`,
    `When a singer's voice is sweet, he is indeed a singer. (2.57)`,
    `The fox lies even to Enlil. (2.58)`,
    `Each fox is even more of a fox than its mother. (2.60)`,
    `If the hearing of the fox is bad, its foot will be crippled. (2.61)`,
    `The fox could not build his own house, so he got a job at his friend's house as a construction worker. (2.62)`,
    `The fox watered (?) the barley with rush (?) water: "Nature has changed its mind." (2.64)`,
    `A fox trod on the hoof of a wild bull: "It didn't hurt (?)!" (2.65)`,
    `The fox had a stick: "Whom shall I hit?" He carried a seal: "What can I challenge?" (2.66)`,
    `The fox, having urinated into the sea, said: "The depths of the sea are my urine!" (2.67)`,
    `He has not yet caught the fox but he is already making a neck-stock for it. (2.68)`,
    `How clever the fox is! He hoots (?) like the \u0161ulu bird. (2.70)`,
    `Tell a lie and then tell the truth: it will be considered a lie. (2.71)`,
    `He who always lies is a messenger from distant places. (2.72)`,
    `Donkey are being ordered; sacks are being hired. (2.73)`,
    `Your helpless donkey's speed has left him. O Enlil, your helpless man's strength has left him. (2.74)`,
    `My donkey was not destined to run quickly; he was destined to bray! (2.75)`,
    `The donkey roared (?); its owner pierced its nostrils (?): "We must get up and away from here! Quickly! Come!" (2.76)`,
    `A donkey eating its own bedding. (2.77)`,
    `A donkey beating its penis against its belly. (2.78)`,
    `For a donkey there is no stench. FOr a donkey there is no washing with soap. (2.79)`,
    `A widow donkey distinguishes itself by breaking wind. (2.80)`,
    `One does not marry a three-year-old wife, as a donkey does. (2.81)`,
    `Two Akkadians lost a donkey. One went after it while the other wasted the day. The one who just sat around--the fault was his. (2.82)`,
    `He is deceitful, like an ox fleeing the threshing-floor. (2.85)`,
    `Furrows are pleasant to a threshing ox. (2.86)`,
    `An ox following round the threshing-floor is not planting seed. (2.87)`,
    `He who eats during the harvest is not removing clods. He who tears out weeds (?) is not sowing seed. (2.88)`,
    `Your dancing (?) ... is like wild cattle grazing. (2.89)`,
    `If the ox kicks up dust, it gets flour in its own eyes. (2.90)`,
    `While the ox is ploughing, the dog is spoiling the deep furrows. (2.91)`,
    `An ox with diarrhea--its dung is a long trail! (2.92)`,
    `A stranger's ox eats grass, while my ox lies hungry. (2.93)`,
    `Once I had escaped the wild bulld, the wild cow confronted me. (2.94)`,
    `The lamentation priest is the depths of the boat. (2.98)`,
    `The lamentation priest hurled his son into the water: "May the city build like me! May the Land live like me! (2.99)`,
    `The lamentation priest wipes his bottom: "One should not remove what belongs to my mistress Inana. (2.100)`,
    `It is the food of the lamentation priest: the pieces are big but the weight is small. (2.104)`,
    `A lamentation priest whose incancations do not sound sweet is highly regarded among lamentation priests! (2.106)`,
    `Slavering dogs waiting for instructions (?) ...: "Where are you going? Come back! Stay!" (2.107)`,
    `Unruly (?), scowling dogs belong to the shameless man. (2.108)`,
    `A sniffing dog entering all the houses. (2.109)`,
    `A dog eating unclean food is a dog which leaves nothing for the next (?) day. (2.110)`,
    `The smith's dog could not overturn the anvil, so it overturned the basket and pot. (2.112)`,
    `Patting the neck of a treacherous dog--patting from the back of the neck. (2.113)`,
    `A dog which knows no home. (2.114)`,
    `The dog thinks it is clever, but to its master ... (2.115)`,
    `A dog descends, a lance descends--each does damage (?) (2.116)`,
    `The dog licks its shriveled penis with its tongue. (2.117)`,
    `In the city with no dogs, the fox is boss. (2.118)`,
    `The good thing is to find it; the bad thing is to lose it. (2.121)`,
    `I have found it--a cause for celebration! I have lost it--my heart does not ache! (2.122)`,
    `The good thing is the beer. The bad thing is the journey. (2.123)`,
    `For his pleasure he got married. On his thinking it over he got divorced. (2.124)`,
    `Their pleasure--their discomfort. Their discomfort--their pleasure. (2.125)`,
    `Says the man lying on the roof to the man living in the house: "It is too bright up here!" (2.126)`,
    `Collecting firewood is for the strong man; the weak man waits for him on dry land. (2.133)`,
    `He who shaves his head acquires ever more hair. And he who gathers firewood acquires ever more grain. (2.134)`,
    `He who destroys houses destroys reeds. He who destroys a house destroys gold. (2.135)`,
    `Hand added to hand, and a man's house is built up. Stomach added to stomach, and a man's house is destroyed. (2.138)`,
    `The hoe cannot cut firewood. The pitchfork cannot cut firewood. (2.139)`,
    `In a household of several grown-up young men, the hoe and the work basket must cultivate the fields. (2.140)`,
    `The mother who has given birth to eight young men lies down exhausted. (2.141)`,
    `The house built by the upright man is destroyed by the treacherous man. (2.142)`,
    `If a household acquaintance has been exposed to harm, the matter is investigated. (2.143)`,
    `Let there be unused land adjacent to a house; let there be a threshing-floor adjacent to a field. (2.144)`,
    `One finds no rest (?) in a house in which a wife does not speak, in which the head of the household (?) does not utter joyous words. (2.146)`,
    `Those who live near the water look into the heart of the mountains. THey don't look in their own direction. (2.149)`,
    `The palace is an ox; catch it by the tail! (2.153)`,
    `The palace is a huge river; its interior is a goring bull. (2.154)`,
    `The palace is a forest. The king is a lion. Nungal overwhelms men with a huge battle-net. Oh Utu, accept my prayer. (2.155)`,
    `The palace is a slippery place which catches those who do not know it. (2.156)`,
    `Through building my house I incurred debt, so I could not afford to cultivate the field I had sowed with seed. (2.159)`,
    `May you be a household built up by twin sons. (2.160)`,
    `I would rather go home. (2.161)`,
    `Those who enter his house are fifty. (2.162)`,
    `Whom can I bring to a house whose offspring have been annihilated? (2.163)`,
    `I don't return to a house whose master is not at home. (2.164)`,
    `A fish in the deep is as good as a carp in the reeds. (2.c3)`,
    `Four-legged creatures are as good as marsh rats. (2.c4)`,
    `All the birds flew away, and their mother alone stayed. (2.c5)`,
    `Ninazu, a bird flying around is your share. (2.c6)`,
    `In the fowler's trap (?) is what he eats. (2.c7)`,
    `He who lives from birds and fish cannot sleep (2.c8)`,
    `What did the ... bird do? (2.c9)`,
    `He sneaks into the water like an um bird. (2.c12)`,
    `The wood pigeon's (?) voice is the glory of the garden. (2.c13)`,
    `The francolin's voice is the glory of the fields. (2.c14)`,
    `Offerings are the glory of the gods. (2.d1)`,
    `Now, you should not sleep in the reedbeds: the marsh rats will eat you. (2.d7)`,
    `Don't pour water into a river. The rats will come up. (2.d9)`,
    `To stand and to sit, to spur on the donkeys, to support (?) the prince: who has the breath for that? (3.1)`,
    `You are peering out from the parapet like the prince's nurse. (3.2)`,
    `Unpleasant ... plants grow towards a good field. (3.4)`,
    `I will feed you even though you are an outcast. I will give you drink even though you are an outcast. You are still my son, even if your god has turned against you. (3.5)`,
    `"I will go today" is what a herdsman says; "I will go tomorrow" is what a shepherd-boy says. "I will go" is "I will go," and time passes. (3.6)`,
    `The churned milk, although it isn't river mud, is diverted into cracks into the ground. (3.7)`,
    `To serve beer with unwashed hands, to spit without trampling upon it, to sneeze without covering it with dust, to kiss with the tongue at midday without providing shade, are abominations to Utu. (3.8)`,
    `A shepherd his penis, a garden his hair. An unjust heir who does not support a wife, or who does not support a child, has no cause for celebration. (3.9)`,
    `If you get rid of the shepherd, then his sheep will not return. (3.10)`,
    `Because the clever shepherd became confused, his sheep did not return. (3.11)`,
    `A shepherd-boy when weary cannot recognize his own mother. (3.12)`,
    `While you still have light, grind the flour. (3.13)`,
    `The wild bull is taboo for the plough. (3.14)`,
    `To eat modestly doesn't kill a man, but to covet will murder you. To eat a little is to live splendidly. When you walk about, keep your feet on the ground! (3.15)`,
    `As long as he is alive, he is his friend. When he is dead, he is his worst demon. (3.16)`,
    `Friendship lasts for just one day, but collegiality lasts forever. (3.17)`,
    `Quarrelling occurs wherever there are colleagues. Slander occurs even when there has been purification. (3.18)`,
    `When travelling, a man does not tire of eating. He gathers in food all day long. (3.19)`,
    `There are bitter tears in human flesh. (3.20)`,
    `Not buying vegetables, a promise (?) not fulfilled (?), handing over worthless money, not removing a mote from the eye. (3.21)`,
    `A hand will stretch out towards an outstretched hand. A hand will open for an opened hand. (3.22)`,
    `He who has silver is happy; he who has grain feels comfortable; he who has livestock can sleep. (3.23)`,
    `Enlil, ..., my loincloth {is} {(1 ms. has instead:) is not} gone (?). (3.24)`,
    `What did Enlil make? Chaff! The lance stuck. It went into the flesh. (3.25)`,
    `When the sun is setting outside so that you cannot even recognize the hand in front of you, go indoors! (3.26)`,
    `Like beer ... in front of him ... (3.32)`,
    `He who says "I will live for today" is bound like a bull on a nose-rope. (3.33)`,
    `Ur-Namma ... large mirrors in Enlil's temple. (3.34)`,
    `Nanni cherished his old age: "I am what an old man should be." (3.35)`,
    `The voluptuous slave girl says: "Let Iškur, ... god ... king ... split the fertile ground like a cucumber." (3.36)`,
    `You grind with the pestle like a fearful slave girl. (3.39)`,
    `The slave girl who neglected to fill the containers grumbled: "It does not fill (?) to the top; it does not fill (?) the middle." (3.40)`,
    `When the lady left the house and the slave girl entered from the street, away from her lady the slave girl sat at her own banquet. (3.41)`,
    `When there is a dispute at the mill, a slave girl reveals (?) what she has stolen. (3.42)`,
    `The joy of a daughter-in-law is anger. (3.44)`,
    `Let me come in! Let me ... it! Let me destroy it! ... (3.46)`,
    `Let me buy it! Let me ... ! (3.48)`,
    `Like a suckling bull ... (3.54)`,
    `As long as you live you should not increase evil by telling lies; for if you do, to succumb will be your lot. (3.55)`,
    `The lord (i.e. An (?)) cursed Unug, but so was he cursed by the lady of E-ana (i.e. Inana). (3.59)`,
    `I am a loyal steward with strong arms. (3.60)`,
    `Let the sides be separated; let me be the one who ... the sides. (3.61)`,
    `It is on account of being the boss that you bully me. (3.62)`,
    `Because of his arrogance, may his head be bowed to his neck like a damp reed. (3.63)`,
    `Weighing scales made with a net are a trap made for the feet; a man should not take a merchant for his friend. (3.64)`,
    `You, merchant, how small you made the amount of silver! And how small you made the amount of oil and barley! (3.65)`,
    `One cannot drag out the weak, one cannot hold back the strong. (3.67)`,
    `Le our odor be the smell of leeks--let it not be the smell of turnips! (3.68)`,
    `He who insults is insulted. He who sneers is sneered at. (3.69)`,
    `A lion caught in the trap in the storehouse becomes mine in this way: the owner simply removes the wood. (3.70)`,
    `A tenant established the house, and ploughing established the field. (3.74)`,
    `"I am stretching my legs on your behalf," says a man delivering sesame. (3.75)`,
    `You invoke the oath of Iškur, who destroys the mountains, but ... you cannot cross the river with a boat. (3.76)`,
    `Iškur splits the mountains, yet he does not split the waterskin. (3.77)`,
    `A runaway slave girl only pretends to sleep. (3.79)`,
    `The gazelle in the ... desert feeds its young with milk. (3.80)`,
    `He moves like a lion against a louse, but when there is a job to be done, he moves like a rat. (3.82)`,
    `As the sun rises, decisions are made. By the time the sun is up, kingship is conferred. (3.83)`,
    `The battle-club would not find out your name--it would just find your flesh. (3.84)`,
    `Our own odor is of pulled-up turnips--sweet things are brought by strangers. (3.85)`,
    `"Give me!" is what the kign says. "Do well!" is what the cupbearer's son says. (3.86)`,
    `He who tosses his head succeeds in crossing the river. (3.88)`,
    `If the foreman does not know how to assign the work, his workers will not stop shaking their heads. (3.89)`,
    `Enlil's temple is a summation of accounts. The temple manager is its overseer. (3.91)`,
    `Enlil's temple is a gathering (?) of wages. (3.92)`,
    `Enlil's greatest punishment is hunger. (3.93)`,
    `If one does not give the dog something, it will bark at every woman. (3.94)`,
    `She growls like a dog struck by a throw-stick. (3.95)`,
    `That which is made of evil threads grumbles. (3.96)`,
    `"Just-let-me-say-a-word" walks like feet. Who can rival a garrulous man? (3.97)`,
    `You speak to me--and I will speak to you! (3.99)`,
    `He who ... is the one who eats something. (3.100)`,
    `You speak with me and I speak with you. (3.101)`,
    `Fools are the ribcages of heroes. (3.102)`,
    `The fool is garrulous. (3.103)`,
    `The dog moves, the knife moves, but still my man does not move. (3.104)`,
    `Where someone is lame, ... the emissary of Bau comes to their aid. (3.105)`,
    `Where there is no grain, this is a sign of vengeance turned towards a city. When there are no reeds, it is the worst of all poverty. (3.106)`,
    `Something offered is not offered. Something finished is not finished. Nothing changes. (3.107)`,
    `A vagrant flays the skin of an opened hand. (3.108)`,
    `The two of them are like one man. (3.109)`,
    `Were he to find where I put my rubbish heap, he would say: "You shoulnd't go there!" (3.110)`,
    `Although it has never been there, the goat knows the wasteland. (3.111)`,
    `With my mouth I cool the hot soup for you. I pick the bones from the fish for you. (3.112)`,
    `My mouth, every month I fill you, my mouth. (3.113)`,
    `My tongue, like a runaway donkey, will not turn back. (3.114)`,
    `All day long my food ration is kept away from me, my heart ..., but even a dog can satisfy its hunger. It's over for me, but should I be happy? My mother would not give me second helpings. (3.115)`,
    `The ox standing in the fodder abandoned the calf to enter the pen. (3.116)`,
    `You may lift it all together but you will put it down in pieces. (3.117)`,
    `When a man comes forward as a witness, saying: "Let me tell you what I know about him," but does not know the relevant information, it is an abomination to Suen. (3.118)`,
    `Flies enter an open mouth. (3.119)`,
    `Offerings create life. (3.120)`,
    `Punishment is assigned for the swaggerer; he is afflicted with diseases. (3.121)`,
    `Let him go down. (3.122)`,
    `You should hold a kid in your right arm, and a bribe in your left arm. (3.123)`,
    `The manicurist is himself dressed in dirty rags. (3.124)`,
    `He came, he stayed a while; he finished, he did not stay put. (3.125)`,
    `My fingernail that hurts is clutched in my embrace. My foot that hurts is in my sandal. But who will find my aching heart? (3.127)`,
    `May Inana pour oil on my heart that aches. (3.128)`,
    `The sail on the mast blocks the river. (3.129)`,
    `May you find the response to an insult hurled at you in a dispute. (3.130)`,
    `If it is too sweet for him, let him eat salt. If it is not too sweet for him, let him eat licorice. (3.131)`,
    `Before the fire has gone out, write your exercise tablet! (3.132)`,
    `A man's personal god is a shepherd who finds pasturage for the man. Let him lead him like sheep to the food they can eat. (3.134)`,
    `As long as the boasters haven't departed, their mouths make me uneasy. (3.135)`,
    `The heavens were destroyed, the earth was shaken. After the heavens were destroyed and the earth was shaken, the people were still standing there on their own. (3.136)`,
    `The rigging is not ship-shape, and the stern is not seaworthy. (3.137)`,
    `He who entered Elam--his lips are sealed. (3.138)`,
    `He who has to live in Elam--his life is not good. (3.139)`,
    `Wheat and hulled barley was made to taste like honey. The nomad ate it and didn't recognize what was in it. (3.140)`,
    `He who keeps fleeing, flees from his own past. (3.141)`,
    `The south wind got its sand into my eyes: "Why do you strike me in the back?" (3.142)`,
    `Between the basket and the boat are the fields of Simurrum. (3.143)`,
    `You keep walking around the storehouse like a pig with a morsel in its mouth. (3.144)`,
    `For him who is rejected by Inana, his dream is to forget. (3.145)`,
    `Whether it is roasted or not, you should sprinkle the grain. (3.146)`,
    `It is characteristic of your harvesting, it is characteristics of your gleaning, that they say: "He is gone, he is gone." (3.147)`,
    `The day became cloudy but it did not rain. It rained, but not enough for people to undo their sandals. The Tigris was not surging at its inlet, so water did not fill the arable lands. (3.149)`,
    `In Eridug, built in abundance, the monkey sits with longing eyes in the singer's house. (3.150)`,
    `Cream and milk are multiplied by an axe. (3.151)`,
    `Let the solitary one remain alone; he is forever treacherous. (3.152)`,
    `The goat spoke in the manner of a wise old woman but acted in the manner of an unclean woman. (3.153)`,
    `The clod in one hand, the furrow on the other hand. And I am the third one there. (3.154)`,
    `Let me drink beer shandy and sit in the seat of honor! (3.155)`,
    `Although it was not important to him, he attended the festival. (3.156)`,
    `The time passed, and what did you gain? (3.157)`,
    `The figure is good. The father-in-law rejoices over it: "It is just like a real person!" (3.158)`,
    `A good word is a friend to numerous men. (3.159)`,
    `A destructive (?) word is four oxen yoked together. (3.160)`,
    `Putting unwashed hands to one's mouth is disgusting. (3.161)`,
    `May a clever farmer live at home with you. (3.162)`,
    `My drink is a river. The play where I sleep is a place of reed mats. (3.163)`,
    `The gecko wears a tiara. (3.164)`,
    `"I'm going home" is what he prefers. (3.165)`,
    `The sun never leaves my heart, which suprasses a garden. (3.166)`,
    `He holds up the sky, letting the earth dangle from his hands. (3.167)`,
    `The muš barley is reserved for the necromancer. (3.168)`,
    `Wheat flour is sacred to his god. (3.169)`,
    `If a man sailing downstream says "Give way!" (?)--if the hand touches a woman's genitals over her clothes--it is an abomination to Suen. (3.170)`,
    `Carrying bread to the oven whilst singing is an abomination to Inana. (3.171)`,
    `The sheep (?) is shrouded in wickedness for him. (3.173)`,
    `If the sieve is not shaken, his flour will not drop from it. (3.174)`,
    `Coveting and reaching out for things are abominations to Ninurta. (3.175)`,
    `I am confronting Fate: "Speak in the way of a just man, or speak in the way of a wicked man, it makes no difference. (3.176)`,
    `What comes out of one's mouth is not in one's hand. (3.177)`,
    `He said: "Woe!" and the boat sank with him. He said: "Alas!" and the rudder broke. (3.179)`,
    `He is walking around despite his wounded neck. (3.180)`,
    `He turns things upside down. (3.181)`,
    `He devours things as crows to a field. (3.182)`,
    `A free weaver equals two slave girls. A free worker equals three slaves. (3.183)`,
    `A spade is a fisherman who does not make ... fly (?).`,
    `My mouth enables me to rival other men. (3.185)`,
    `What is this after you split it? And this after you split it?`,
    `When present, it was considered a loincloth; when lost, it is considered fine clothing. (3.187)`,
    `If the leader is being devoured by a fire, those behind him don't say: "Where is the leader?" (1.88)`,
    `To call out from among (?) the people. (3.189)`,
    `When righteousness is cut off, injustice is increased. (3.190)`
]

module.exports = sumerSays;