var sumerSays = [
    `Who can compete with righteousness? It creates life. (1.1)`,
    `If wickedness exerts itself, how will Utu succeed? (1.2)`,
    `You should not cut the throat of that which has already had its throat cut. (1.3)`,
    `You should not say to Ningi\u0161zida: "Let me live!" (1.4)`,
    `Do not make me pass through the gate! (1.5)`,
    `What has submitted will exhibit resistance. (1.6)`,
    `What has been destroyed belongs to a god. No one is able to take it away. (1.7)`,
    `"Though I still have bread left over, I will eat your bread!" Will this endear a man to the household of his friend? (1.8)`,
    `If bread is leftover, the mongoose eats it. If I have any bread left over, then a stranger will eat it. (1.9)`,
    `My things changed things. (1.10)`,
    `You don't speak of that which you have found. You talk only about what you have lost. (1.11)`,
    `Something which has never occurred since time immemorial: a young woman did not fart in her husband's embrace. (1.12)`,
    `It is a thing of short duration. (1.13)`,
    `Whatever it is that hurts you, don't talk to anyone about it. (1.14)`,
    `Wealth is far away, poverty is close at hand. (1.15)`,
    `He who possesses many things is constantly on guard. (1.16)`,
    `Possessions make trust of crucial importance. (1.17)`,
    `Possessions are flying birds--they never find a place to settle. (1.18)`,
    `Good fortune is embedded in organization and wisdom. (1.19)`,
    `What is eaten for today (?) was put there by the dog. What is eaten by the dog was put there for today (?). (1.20)`,
    `One shouldn't scorn bread which has turned bad. (1.21)`,
    `Give out only half a loaf voluntarily! (1.22)`,
    `To be wealthy and insist on demanding more is abominable. (1.23)`,
    `Let him decree the fates while consuming what you have made. (1.26)`,
    `I always seem to be speaking about unpleasant things. (1.27)`,
    `When a purchase is settled it is soon out of mind. (1.28)`,
    `He did something never seen before. (1.29)`,
    `That which does not eat grass is a wild bull of the mountains. That which does not drink water is a gazelle of the mountains. (1.30)`,
    `One does not returned borrowed bread. (1.31)`,
    `The herald rejoices when the estate makes expenditures. (1.32)`,
    `The steward rejoices when the estate increases its income. (1.33)`,
    `Don't pick things now; they will bear fruit later. (1.35)`,
    `Who will listen to your translations? (1.36)`,
    `What you are doing is a small accomplishment. That man is not doing a man's work. (1.37)`,
    `Let his bread be foul food; no man should eat it. (1.40)`,
    `Let his food be bread and ... eggs, so that it clogs his throat. (1.41)`,
    `Let his food be ... bones, so that it sticks in his throat. (1.42)`,
    `Barley flour, in the fields, is meat fat. (1.48)`,
    `Whatever food is available in the fields is to be eaten alone. (1.49)`,
    `Chickpea-flour is appropriate for every woman in the palace. (1.50)`,
    `His bread is finished. (1.51)`,
    `There is no baked cake in the middle of the dough. (1.52)`,
    `Give me my tools and I will launch my boat. (1.54)`,
    `When he walks on the streets no one greets him. And when he comes home to his wife, "Bad Name" is what he is called. (1.56)`,
    `The lives of the poor do not survive their deaths. (1.57)`,
    `In the city where there are no dogs, the fox is boss. (1.65)`,
    `You should drive them like pack-assess into a death-stricken city (1.68)`,
    `Like a clod thrown into the water, may it be destroyed as it disintegrates. (1.76)`,
    `Beer is a bull. The mouth is its stairway. (1.77)`,
    `It is an insult resulting from an insult. It is a curse resulting from a curse. It is the constant renewal of destiny. (1.80)`,
    `To accept a verdict is possible. To accept a curse is impossible. (1.81)`,
    `My girlfriend's heart is a heart made for me. (1.91)`,
    `He broke it into pieces and sated his hunger. He licked his hands and belched. (1.101)`,
    `He who drinks beer drinks water. (1.102)`,
    `A heart never created hatred; speech created hatred. (1.105)`,
    `(line fragmentary)`,
    `You cannot butt me with your horns! Who is it that you are butting! You cannot kill me--I am running away! (1.109)`,
    `My husband heaps up for me, my child measures out for me; let my lover pick the bones from the fish for me. (1.125)`,
    `A plant as sweet as a husband does not grow in the steppe. (1.126)`,
    `In the sky there is the raven; on the earth there is the mongoose; in the desert there is the lion ...; my husband! Where shall I go? (1.128)`,
    `...the brothers in anger destroyed their father's estate. (1.141)`,
    `Thus my mother and my younger sister act toward me; ... am I so deficient in judgment that I should offer my cheek to her? (1.143)`,
    `You are not one who stays in one place, you are one who is everywhere. (1.144)`,
    `Accept your lot and make your mother happy. Run fast and make your god happy. (1.145)`,
    `Marry a wife according to your choice. Have children to your heart's content. (1.146)`,
    `Girl, your brother cannot choose for you; whom do you choose? (1.148)`,
    `Girl, your brother is like me. A brother should let you live as would I. (1.149)`,
    `When I married a malicious husband, when I bore a malicious son, an unhappy heart was assigned to me. (1.151)`,
    `He who does not support a wife, he who does not support a child, has no cause for celebration. (1.153)`,
    `A malicious wife living in the house is worse than all diseases. (1.154)`,
    `My wife said "Unfaithful!" to me--shall I go chasing after women's genitals? (1.158)`,
    `An unfaithful penis matches an unfaithful vagina. (1.159)`,
    `What...? A tradesman gave it to me... (1.164)`,
    `I walk about, I don't get tired. I keep moving, I don't sleep. (1.174)`,
    `When the rags have been cut up, when the barley is lying in the dust, what is there left to get? (1.175)`,
    `I am a lady who wears large garments. Let me cut my loincloth! (1.176)`,
    `When you are eating, may nothing lack. When you are in need of water, may things not dry up. (1.178)`,
    `A chattering girl is silenced by her mother. A chattering boy is not silenced by his mother. (1.185)`,
    `To be sick is acceptable; to be pregnant is painful; but to be pregnant and sick is just too much. (1.193-194)`,
    `Let me explain it to you: it is a disgrace. (2.1)`,
    `Were I to tell my neighbor about my fate, he would heap insults upon me. (2.3)`,
    `I looked into the water. My destiny was drifting past. (2.4)`,
    `I was born on an ill-fated day. (2.15)`,
    `Fate is a dog--well able to bite. Like dirty rags, it clings, saying: "Who is my man? Let him know it." (2.11)`,
    `Fate is a cloth stretched out in the desert for a man. (2.12)`,
    `Fate is a raging storm blowing over the Land. (2.13)`,
    `Fate is a dog walking always behind a man. (2.14)`,
    `The poor man must always look to his next meal. (2.15)`,
    `The belching poor man should not look scornfully at the rich man. (2.16)`,
    `How can a poor man who doesn't know how to cultivate barley manage to cultivate wheat? (2.17)`,
    `The poor man is not appreciated. (2.18)`,
    `The poor man chews whatever he is given. (2.19)`,
    `He didn't plough the field during winter. And at harvest time he turned his hand to carding. (2.20)`,
    `Not all the households of the poor will bow down together. (2.26)`,
    `The word of the poor man is not accepted. (2.27)`,
    `Moving about defeats poverty. He who knows how to move around becomes strong. He will live longer than the sedentary man. (2.28)`,
    `The poor man is this lowly: his debts are paid off with what is taken from his mouth. (2.30)`,
    `You are a scribe and you do not know your own name? Shame on you! (2.37)`,
    `If a scribe knows only a single line but his handwriting is good, he is indeed a scribe! (2.38)`,
    `If a singer knows only one song but makes the sound pleasant, he is indeed a singer! (2.39)`,
    `A scribe whose hand can follow dictation is indeed a scribe! (2.40)`,
    `A singer whose voice is not sweet is a wretch among singers! (2.41)`,
    `A wretched scribe, the most backward in the school! (2.42)`,
    `A scribe without a hand. A singer without a throat. (2.43)`,
    `You are an outstanding scribe; you are no lowly man. (2.44)`,
    `The pupil of a master, like cornelian pierced through its side. He is indeed a scribe! (2.45)`,
    `That which is pierced through its side is indeed lapis lazuli! (2.46)`,
    `What kind of scribe is a scribe who does not know Sumerian? (2.47)`,
    `Someone who cannot produce "a-a"--from where will he achieve fluent speech? (2.48)`,
    `A scribe who does not know Sumerian--from where will he produce a translation? (2.49)`,
    `The scribe trained in counting is deficient on clay. The scribe skilled with clay is deficient in counting. (2.50)`,
    `You are a ... scribe ... (2.51)`,
    `A chattering scribe's guilt is great. (2.52)`,
    `A junior scribe is too concerned with feeding his hunger; he does not pay attention to the scribal art. (2.53)`,
    `A scribe who does not know how to grasp the meaning--from where will he produce a translation? (2.56)`,
    `When a singer's voice is sweet, he is indeed a singer. (2.57)`,
    `The fox lies even to Enlil. (2.58)`,
    `Each fox is even more of a fox than its mother. (2.60)`,
    `If the hearing of the fox is bad, its foot will be crippled. (2.61)`,
    `The fox could not build his own house, so he got a job at his friend's house as a construction worker. (2.62)`,
    `The fox watered (?) the barley with rush (?) water: "Nature has changed its mind." (2.64)`,
    `A fox trod on the hoof of a wild bull: "It didn't hurt (?)!" (2.65)`,
    `The fox had a stick: "Whom shall I hit?" He carried a seal: "What can I challenge?" (2.66)`,
    `The fox, having urinated into the sea, said: "The depths of the sea are my urine!" (2.67)`,
    `He has not yet caught the fox but he is already making a neck-stock for it. (2.68)`,
    `How clever the fox is! He hoots (?) like the \u0161ulu bird. (2.70)`,
    `Tell a lie and then tell the truth: it will be considered a lie. (2.71)`,
    `He who always lies is a messenger from distant places. (2.72)`,
    `Donkey are being ordered; sacks are being hired. (2.73)`,
    `Your helpless donkey's speed has left him. O Enlil, your helpless man's strength has left him. (2.74)`,
    `My donkey was not destined to run quickly; he was destined to bray! (2.75)`,
    `The donkey roared (?); its owner pierced its nostrils (?): "We must get up and away from here! Quickly! Come!" (2.76)`,
    `A donkey eating its own bedding. (2.77)`,
    `A donkey beating its penis against its belly. (2.78)`,
    `For a donkey there is no stench. FOr a donkey there is no washing with soap. (2.79)`,
    `A widow donkey distinguishes itself by breaking wind. (2.80)`,
    `One does not marry a three-year-old wife, as a donkey does. (2.81)`,
    `Two Akkadians lost a donkey. One went after it while the other wasted the day. The one who just sat around--the fault was his. (2.82)`,
    `He is deceitful, like an ox fleeing the threshing-floor. (2.85)`,
    `Furrows are pleasant to a threshing ox. (2.86)`,
    `An ox following round the threshing-floor is not planting seed. (2.87)`,
    `He who eats during the harvest is not removing clods. He who tears out weeds (?) is not sowing seed. (2.88)`,
    `Your dancing (?) ... is like wild cattle grazing. (2.89)`,
    `If the ox kicks up dust, it gets flour in its own eyes. (2.90)`,
    `While the ox is ploughing, the dog is spoiling the deep furrows. (2.91)`,
    `An ox with diarrhea--its dung is a long trail! (2.92)`,
    `A stranger's ox eats grass, while my ox lies hungry. (2.93)`,
    `Once I had escaped the wild bulld, the wild cow confronted me. (2.94)`,
    `The lamentation priest is the depths of the boat. (2.98)`,
    `The lamentation priest hurled his son into the water: "May the city build like me! May the Land live like me! (2.99)`,
    `The lamentation priest wipes his bottom: "One should not remove what belongs to my mistress Inana. (2.100)`,
    `It is the food of the lamentation priest: the pieces are big but the weight is small. (2.104)`,
    `A lamentation priest whose incancations do not sound sweet is highly regarded among lamentation priests! (2.106)`,
    `Slavering dogs waiting for instructions (?) ...: "Where are you going? Come back! Stay!" (2.107)`,
    `Unruly (?), scowling dogs belong to the shameless man. (2.108)`,
    `A sniffing dog entering all the houses. (2.109)`,
    `A dog eating unclean food is a dog which leaves nothing for the next (?) day. (2.110)`,
    `The smith's dog could not overturn the anvil, so it overturned the basket and pot. (2.112)`,
    `Patting the neck of a treacherous dog--patting from the back of the neck. (2.113)`,
    `A dog which knows no home. (2.114)`,
    `The dog thinks it is clever, but to its master ... (2.115)`,
    `A dog descends, a lance descends--each does damage (?) (2.116)`,
    `The dog licks its shriveled penis with its tongue. (2.117)`,
    `In the city with no dogs, the fox is boss. (2.118)`,
    `The good thing is to find it; the bad thing is to lose it. (2.121)`,
    `I have found it--a cause for celebration! I have lost it--my heart does not ache! (2.122)`,
    `The good thing is the beer. The bad thing is the journey. (2.123)`,
    `For his pleasure he got married. On his thinking it over he got divorced. (2.124)`,
    `Their pleasure--their discomfort. Their discomfort--their pleasure. (2.125)`,
    `Says the man lying on the roof to the man living in the house: "It is too bright up here!" (2.126)`,
    `Collecting firewood is for the strong man; the weak man waits for him on dry land. (2.133)`,
    `He who shaves his head acquires ever more hair. And he who gathers firewood acquires ever more grain. (2.134)`,
    `He who destroys houses destroys reeds. He who destroys a house destroys gold. (2.135)`,
    `Hand added to hand, and a man's house is built up. Stomach added to stomach, and a man's house is destroyed. (2.138)`,
    `The hoe cannot cut firewood. The pitchfork cannot cut firewood. (2.139)`,
    `In a household of several grown-up young men, the hoe and the work basket must cultivate the fields. (2.140)`,
    `The mother who has given birth to eight young men lies down exhausted. (2.141)`,
    `The house built by the upright man is destroyed by the treacherous man. (2.142)`,
    `If a household acquaintance has been exposed to harm, the matter is investigated. (2.143)`,
    `Let there be unused land adjacent to a house; let there be a threshing-floor adjacent to a field. (2.144)`,
    `One finds no rest (?) in a house in which a wife does not speak, in which the head of the household (?) does not utter joyous words. (2.146)`,
    `Those who live near the water look into the heart of the mountains. THey don't look in their own direction. (2.149)`,
    `The palace is an ox; catch it by the tail! (2.153)`,
    `The palace is a huge river; its interior is a goring bull. (2.154)`,
    `The palace is a forest. The king is a lion. Nungal overwhelms men with a huge battle-net. Oh Utu, accept my prayer. (2.155)`,
    `The palace is a slippery place which catches those who do not know it. (2.156)`,
    `Through building my house I incurred debt, so I could not afford to cultivate the field I had sowed with seed. (2.159)`,
    `May you be a household built up by twin sons. (2.160)`,
    `I would rather go home. (2.161)`,
    `Those who enter his house are fifty. (2.162)`,
    `Whom can I bring to a house whose offspring have been annihilated? (2.163)`,
    `I don't return to a house whose master is not at home. (2.164)`,
    `A fish in the deep is as good as a carp in the reeds. (2.c3)`,
    `Four-legged creatures are as good as marsh rats. (2.c4)`,
    `All the birds flew away, and their mother alone stayed. (2.c5)`,
    `Ninazu, a bird flying around is your share. (2.c6)`,
    `In the fowler's trap (?) is what he eats. (2.c7)`,
    `He who lives from birds and fish cannot sleep (2.c8)`,
    `What did the ... bird do? (2.c9)`,
    `He sneaks into the water like an um bird. (2.c12)`,
    `The wood pigeon's (?) voice is the glory of the garden. (2.c13)`,
    `The francolin's voice is the glory of the fields. (2.c14)`,
    `Offerings are the glory of the gods. (2.d1)`,
    `Now, you should not sleep in the reedbeds: the marsh rats will eat you. (2.d7)`,
    `Don't pour water into a river. The rats will come up. (2.d9)`
]

module.exports = sumerSays;